apiVersion: v2
name: genieacs
description: A Helm chart for GenieACS - an open-source implementation of TR-069 ACS
type: application
version: 0.4.0
appVersion: "1.2.16.0"
keywords:
  - genieacs
  - tr-069
  - acs
  - cpe
  - device-management
home: https://genieacs.com
sources:
  - https://github.com/genieacs/genieacs
maintainers:
  - name: Sergio Fernandez
    email: acsdesk@protonmail.com
annotations:
  category: Infrastructure
dependencies:
  - name: mongodb
    version: 18.6.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mongodb.enabled