# Chart Releaser configuration
owner: GeiserX
git-repo-url: https://github.com/GeiserX/genieacs-docker
charts-repo-url: https://geiserx.github.io/genieacs-docker
packages-with-index: false
index-path: index.yaml
release-name-template: "{{ .Name }}-{{ .Version }}"

