context: test-cluster

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: mongodb-genieacs
    namespace: genieacs
    chart: bitnami/mongodb
    version: 10.31.4
    labels:
      app: mongodb
      release: genieacs
    values:
      - mongo.yaml
    
  - name: genieacs
    namespace: genieacs
    chart: ../charts/genieacs/
    version: 0.1.0
    labels:
      app: genieacs
      release: genieacs
    values:
      - genieacs.yaml