context: test-cluster

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: genieacs
    url: https://geiserx.github.io/genieacs-docker

releases:
  - name: mongodb-genieacs
    namespace: genieacs
    chart: bitnami/mongodb
    version: 10.31.4
    labels:
      app: mongodb
      release: genieacs
    values:
      - mongo.yaml
    
  - name: genieacs
    namespace: genieacs
    chart: genieacs/genieacs
    version: 0.1.1
    labels:
      app: genieacs
      release: genieacs
    values:
      - genieacs.yaml