repositories:
  - name: genieacs
    url: https://geiserx.github.io/genieacs-docker

releases:
  - name: genieacs
    namespace: genieacs
    chart: genieacs/genieacs
    # renovate: registryUrl=https://geiserx.github.io/genieacs-docker
    version: 0.3.3
    labels:
      app: genieacs
    values:
      - genieacs.yaml
    secrets:
      - genieacs-secrets.yaml
