apiVersion: v1 #Store this file apart from the main deployment in a safe location. Must be deployed before the rest.
data:
  mongodb-password: REDACTED_BASE64 #REDACTED , please change and encode base64
  mongodb-root-password: REDACTED_BASE64 #REDACTED , please change and encode base64
kind: Secret
metadata:
  name: genieacs-mongo
  namespace: genieacs # Change if you deploy to another namespace
type: Opaque
